name: appengine
version: 0.7.0
author: Dart Team <misc@dartlang.org>
description: Support for using Dart as a custom runtime on Google App Engine Flexible Environment
homepage: https://github.com/dart-lang/appengine

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  fixnum: '>=0.9.0 <0.11.0'
  gcloud: '^0.6.0'
  googleapis_auth: '>=0.2.3+6 <0.3.0'
  http: '>=0.11.3+9 <0.13.0'
  http_server: '^0.9.2'
  http2: '>=0.1.1+2 <2.0.0'
  logging: '>=0.9.3 <0.12.0'
  path: '^1.2.0'
  protobuf: '^0.13.11'
  stack_trace: '^1.9.0'

dev_dependencies:
  test: '^1.3.0'
  pedantic: '^1.7.0'
